### ISSUE TITLE
spike: June Technical Roadmap

### ISSUE THREAD

**Issue by boudra** [gitcoinco/allo-indexer#91]
# Objectives

The indexer has been crucial in providing data to the Grants Stack application and the DAO. It also provides round operators with matching calculations which are at the core of what we do. As the reliance on the indexer grows, it becomes an even more important piece of our infrastructure.

During the beta rounds we experienced some issues that, although they quickly resolved, their occurrence and timing was very unfortunate and time-consuming for the team. Most of the issues were not caught by the development team, but by PGF, we cannot rely on other teams to do the testing for us and we should be able to catch issues earlier.

Even though there were also non-technical factors that played a part that we also have to resolve, the bottom line is that we can prevent these types of issues entirely with improvements on the technical side.

Given our current capacity and breathing room, we are now better positioned to improve the reliability of the indexer. This is a suggested technical roadmap for the indexer, with lessons learned from the beta rounds.

The objectives of this roadmap are the following:

- Improve observability and ability to analyze the data and the calculations
- Implement safety nets
- Build automated tooling to test and verify the data and the calculations
- Implement automated tests for all features, prioritizing the calculations
- Increase the ability of the whole team to help with the indexer

-----------------

## Debugging and observability

At the moment the indexer is like a black box and we don't have much implemented in terms of debugging, all we can do is download the data and manually check it, we must implement some tooling and expand the endpoints to give more information about whats happening in the indexer.

This should be helpful for development, for PGF and even the community to be able to check what's going on without having to guess or ask the developers.
 
- [ ] Extend matching calculation endpoint to return more information: https://github.com/gitcoinco/grants-stack/issues/1972
   - All the settings used (match amount, passport, min donation, cap, saturation etc.)
   - All the actual contributions (both counted and not counted)
   - For each contribution show all the final coefficient from overrides and other criteria (min donation, passport etc.)
   - For each contribution show the price used to convert between tokens
- [ ] Implement endpoint that shows the indexer's status, how many contracts it's currently indexing, on what block it's indexed up to, how many events it indexed etc.

## Automated testing and tooling

We currently have some gaps in our automated tests, let's make sure all the features are covered.

- [x] Vote coefficient overrides test
- [x] Basic calculation endpoint test
- [x] Saturation test
- [ ] Implement current beta round results as regression tests (calculations, votes, applications)
- [ ] Minimum Amount Integration Test
- [ ] Matching Cap Integration Test
- [ ] Passport Eligibility Integration Test
- [ ] **Low priority:** Indexer event handler test

We can leverage some tooling to ensure code quality:

- [ ] Stricter Linter (enforce Typescript typing) https://github.com/gitcoinco/allo-indexer/pull/77
- [ ] Formatting Check in CI
- [ ] **Low priority:** Automatic testing coverage tracking: https://codecov.io

## Manual testing & quality control

The scale of the data makes it difficult to be tested manually, as developers we can test that features are responding correctly and test with a small dataset but it's very difficult to check the correctness of the data of real rounds by hand.

We can create tooling that helps us verify the data being served, to allow the development team and people outside to test and verify it.

- [x] Implement a staging environment to test new features without having to deploy to production https://github.com/gitcoinco/allo-indexer/issues/90
- [ ] Implement a regression test script to be run manually to diff two indexer endpoints, it can be useful to verify that a  new indexer version serves the same results as the production one
- [ ] [Implement an automated regression test with data from production of running rounds](https://github.com/gitcoinco/allo-indexer/issues/99)
- [ ] [Implement an automated test of the indexer using a local node](https://github.com/gitcoinco/grants-stack/issues/1971)

---

- [ ] Implement separate script to index votes directly from the blockchain and compare values with the Indexer (Maybe Baoki or Umar can help here?) (can we leverage Dune?)

## Refactor and code improvements

- [x] Calculations and Vote Coefficient exports should derive from the same source of truth https://github.com/gitcoinco/allo-indexer/pull/82
- [x] Ensure the indexer crashes on any error to avoid serving incorrect data: https://github.com/gitcoinco/allo-indexer/pull/86

## Scalability

- [x] Use persistent volumes to allow more data to be indexed: https://github.com/gitcoinco/allo-indexer/issues/88
- [x] High availability through horizontal scaling (we haven't had any issues with uptime, but we have to be prepared)
- [ ] Performance testing (the indexer is mostly a static file server so performance is not a big worry but it's beneficial to understand the load it an handle)

## Documentation

Most of it is documented here but we need to make it accessible through Github: https://docs.google.com/presentation/d/1c695Lf5ymVr31Btb7e7erKApXpBPmvf9AXMaKcT_Jq8/edit#slide=id.g22c82fc12dd_3_0

Write documentation for:

- [ ] Indexer architecture
- [ ] Deployment process
- [ ] HTTP endpoint usage
- [ ] Scripts
- [ ] Dashboards
