### ISSUE TITLE
[TODO: break this out into five tickets] Indexer Automated Testing and Tooling

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/allo-indexer#94]
Implement important missing tests from features implemented in the finalize round feature:

- [ ]  Passport Eligibility Integration Test (start with this test first, create template that we can use for other integration tests) -> 2 points 
- [ ]  Minimum Amount Integration Test - 1 point 
- [ ]  Matching Cap Integration Test - 1 point 

- [ ] Implement current beta round results as regression tests (calculations, votes, applications) - 1 point 
- [ ]  Low priority: Indexer event handler test - Need More Info
